### ISSUE TITLE
$.ajax question

### ISSUE THREAD

**Issue by hodiizidor** [alexanderscott/backbone-login#24]
Shouldn't you use Backbone.ajax instead $.ajax calls?

For example [here](https://github.com/alexanderscott/backbone-login/blob/master/public/models/SessionModel.js#L73).

**Comment by alexanderscott** [comment]
From their docs:

```
If you want to use a custom AJAX function, or your endpoint doesn't support the jQuery.ajax API and you need to tweak things, you can do so by setting Backbone.ajax.
```

jQuery.ajax is standard, and we have no need to modify or tweak.   jQuery is also a Backbone.js dependency so we get it for free.
