### ISSUE TITLE
Function close is missing

### ISSUE THREAD

**Issue by Frankistan** [alexanderscott/backbone-login#7]
Hello,
I've noticed that within the public/router.js file , line 36 ,you used a function called "close" but... I don't know where it is created.
Could you possibly add it or tell me where is it declared?
Thanks ;D

**Comment by alexanderscott** [comment]
Nice catch @Frankistan !  I forgot to add this method to the `Backbone.View` prototype - it can be used for view garbage collection (removing from the DOM and unbinding listeners).  From debugging I couldn't find a case where this was being called, but it is a good practice to implement this GC from the router.  I have added and merged with pull #8 .
